### ISSUE TITLE
Search bar on Android 13 is not visible

### ISSUE THREAD

**Issue by efstathiosntonas** [b0iq/react-native-place-picker#10]
On Android 13 on a Samsung S22 the search bar is not visible, I had to guess and tap on the far right. Look video demo:

https://github.com/b0iq/react-native-place-picker/assets/717975/015d23f5-0690-4b0a-9ee0-682a86b338b9

**Expected behavior**
I would expect the search bar to be on the left (and visible ofcourse) and the buttons on the right.

**Smartphone (please complete the following information):**
 - Device: Samsung S22
 - OS: Android 13

**Comment by b0iq** [comment]
Hmmm, I want to reproduce this issue.
Is it empty react-native app?

**Comment by efstathiosntonas** [comment]
It’s not an empty project, will create a repro tomorrow

**Comment by b0iq** [comment]
I will close this issue until hearing a feedback from you.
