### ISSUE TITLE
After searching for a location, cancel text should be "ok" next to the search bar.

### ISSUE THREAD

**Issue by efstathiosntonas** [b0iq/react-native-place-picker#9]
After searching for a location the "cancel" button stays "cancel" instead of "ok" (or something else eg. "done"). This can be confusing to the users.

https://github.com/b0iq/react-native-place-picker/assets/717975/0630fdfd-882f-4500-aea6-14d2f5bf1a1d

thanks for this module!!

**Comment by mjroeleveld** [comment]
@b0iq is this an easy fix? It's quite a big UI issue, people are really confused by this 😬

**Comment by b0iq** [comment]
> @b0iq is this an easy fix? It's quite a big UI issue, people are really confused by this 😬
 I was quite busy last month, I will try to fix it now.
Sorry about this confusion.

**Comment by mjroeleveld** [comment]
@b0iq thanks a lot!
